// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/public/v1/public.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetCaptchaRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetCaptchaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCaptchaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCaptchaRequestMultiError, or nil if none found.
func (m *GetCaptchaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCaptchaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetCaptchaRequestMultiError(errors)
	}

	return nil
}

// GetCaptchaRequestMultiError is an error wrapping multiple validation errors
// returned by GetCaptchaRequest.ValidateAll() if the designated constraints
// aren't met.
type GetCaptchaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCaptchaRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCaptchaRequestMultiError) AllErrors() []error { return m }

// GetCaptchaRequestValidationError is the validation error returned by
// GetCaptchaRequest.Validate if the designated constraints aren't met.
type GetCaptchaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCaptchaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCaptchaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCaptchaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCaptchaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCaptchaRequestValidationError) ErrorName() string {
	return "GetCaptchaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCaptchaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCaptchaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCaptchaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCaptchaRequestValidationError{}

// Validate checks the field values on GetCaptchaReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetCaptchaReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCaptchaReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCaptchaReplyMultiError, or nil if none found.
func (m *GetCaptchaReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCaptchaReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CaptchaId

	// no validation rules for ImageB64

	if len(errors) > 0 {
		return GetCaptchaReplyMultiError(errors)
	}

	return nil
}

// GetCaptchaReplyMultiError is an error wrapping multiple validation errors
// returned by GetCaptchaReply.ValidateAll() if the designated constraints
// aren't met.
type GetCaptchaReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCaptchaReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCaptchaReplyMultiError) AllErrors() []error { return m }

// GetCaptchaReplyValidationError is the validation error returned by
// GetCaptchaReply.Validate if the designated constraints aren't met.
type GetCaptchaReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCaptchaReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCaptchaReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCaptchaReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCaptchaReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCaptchaReplyValidationError) ErrorName() string { return "GetCaptchaReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetCaptchaReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCaptchaReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCaptchaReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCaptchaReplyValidationError{}

// Validate checks the field values on SendSmsOtpRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SendSmsOtpRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendSmsOtpRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendSmsOtpRequestMultiError, or nil if none found.
func (m *SendSmsOtpRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendSmsOtpRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_SendSmsOtpRequest_Mobile_Pattern.MatchString(m.GetMobile()) {
		err := SendSmsOtpRequestValidationError{
			field:  "Mobile",
			reason: "value does not match regex pattern \"^1[3-9]\\\\d{9}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for CaptchaId

	// no validation rules for Captcha

	if _, ok := _SendSmsOtpRequest_Scene_NotInLookup[m.GetScene()]; ok {
		err := SendSmsOtpRequestValidationError{
			field:  "Scene",
			reason: "value must not be in list [UNSPECIFIED]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := SmsOtpScene_name[int32(m.GetScene())]; !ok {
		err := SendSmsOtpRequestValidationError{
			field:  "Scene",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SendSmsOtpRequestMultiError(errors)
	}

	return nil
}

// SendSmsOtpRequestMultiError is an error wrapping multiple validation errors
// returned by SendSmsOtpRequest.ValidateAll() if the designated constraints
// aren't met.
type SendSmsOtpRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendSmsOtpRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendSmsOtpRequestMultiError) AllErrors() []error { return m }

// SendSmsOtpRequestValidationError is the validation error returned by
// SendSmsOtpRequest.Validate if the designated constraints aren't met.
type SendSmsOtpRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendSmsOtpRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendSmsOtpRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendSmsOtpRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendSmsOtpRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendSmsOtpRequestValidationError) ErrorName() string {
	return "SendSmsOtpRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendSmsOtpRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendSmsOtpRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendSmsOtpRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendSmsOtpRequestValidationError{}

var _SendSmsOtpRequest_Mobile_Pattern = regexp.MustCompile("^1[3-9]\\d{9}$")

var _SendSmsOtpRequest_Scene_NotInLookup = map[SmsOtpScene]struct{}{
	0: {},
}

// Validate checks the field values on SendSmsOtpReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SendSmsOtpReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendSmsOtpReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendSmsOtpReplyMultiError, or nil if none found.
func (m *SendSmsOtpReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SendSmsOtpReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExpireAt

	if len(errors) > 0 {
		return SendSmsOtpReplyMultiError(errors)
	}

	return nil
}

// SendSmsOtpReplyMultiError is an error wrapping multiple validation errors
// returned by SendSmsOtpReply.ValidateAll() if the designated constraints
// aren't met.
type SendSmsOtpReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendSmsOtpReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendSmsOtpReplyMultiError) AllErrors() []error { return m }

// SendSmsOtpReplyValidationError is the validation error returned by
// SendSmsOtpReply.Validate if the designated constraints aren't met.
type SendSmsOtpReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendSmsOtpReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendSmsOtpReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendSmsOtpReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendSmsOtpReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendSmsOtpReplyValidationError) ErrorName() string { return "SendSmsOtpReplyValidationError" }

// Error satisfies the builtin error interface
func (e SendSmsOtpReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendSmsOtpReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendSmsOtpReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendSmsOtpReplyValidationError{}
