// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: public/v1/public.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 发送短信验证码 ==========
// 短信验证码场景
type SmsCodeScene int32

const (
	// 未指定（默认值，不应使用）
	SmsCodeScene_UNSPECIFIED SmsCodeScene = 0
	// 登录
	SmsCodeScene_LOGIN SmsCodeScene = 1
	// 注册
	SmsCodeScene_REGISTER SmsCodeScene = 2
	// 忘记密码
	SmsCodeScene_FORGET SmsCodeScene = 3
	// 绑定
	SmsCodeScene_BIND SmsCodeScene = 4
)

// Enum value maps for SmsCodeScene.
var (
	SmsCodeScene_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LOGIN",
		2: "REGISTER",
		3: "FORGET",
		4: "BIND",
	}
	SmsCodeScene_value = map[string]int32{
		"UNSPECIFIED": 0,
		"LOGIN":       1,
		"REGISTER":    2,
		"FORGET":      3,
		"BIND":        4,
	}
)

func (x SmsCodeScene) Enum() *SmsCodeScene {
	p := new(SmsCodeScene)
	*p = x
	return p
}

func (x SmsCodeScene) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmsCodeScene) Descriptor() protoreflect.EnumDescriptor {
	return file_public_v1_public_proto_enumTypes[0].Descriptor()
}

func (SmsCodeScene) Type() protoreflect.EnumType {
	return &file_public_v1_public_proto_enumTypes[0]
}

func (x SmsCodeScene) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmsCodeScene.Descriptor instead.
func (SmsCodeScene) EnumDescriptor() ([]byte, []int) {
	return file_public_v1_public_proto_rawDescGZIP(), []int{0}
}

// ========== 获取图形验证码 ==========
type GetCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaRequest) Reset() {
	*x = GetCaptchaRequest{}
	mi := &file_public_v1_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaRequest) ProtoMessage() {}

func (x *GetCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_v1_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_public_v1_public_proto_rawDescGZIP(), []int{0}
}

type GetCaptchaReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码ID
	CaptchaId string `protobuf:"bytes,1,opt,name=captcha_id,proto3" json:"captcha_id,omitempty"`
	// Base64编码的图片
	ImageB64      string `protobuf:"bytes,2,opt,name=image_b64,proto3" json:"image_b64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaReply) Reset() {
	*x = GetCaptchaReply{}
	mi := &file_public_v1_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaReply) ProtoMessage() {}

func (x *GetCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_public_v1_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaReply.ProtoReflect.Descriptor instead.
func (*GetCaptchaReply) Descriptor() ([]byte, []int) {
	return file_public_v1_public_proto_rawDescGZIP(), []int{1}
}

func (x *GetCaptchaReply) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *GetCaptchaReply) GetImageB64() string {
	if x != nil {
		return x.ImageB64
	}
	return ""
}

type SendSmsCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 手机号，规则：11位数字
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 图形验证码ID
	CaptchaId string `protobuf:"bytes,2,opt,name=captcha_id,proto3" json:"captcha_id,omitempty"`
	// 图形验证码
	Captcha string `protobuf:"bytes,3,opt,name=captcha,proto3" json:"captcha,omitempty"`
	// 验证码场景
	Scene         SmsCodeScene `protobuf:"varint,4,opt,name=scene,proto3,enum=api.public.v1.SmsCodeScene" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsCodeRequest) Reset() {
	*x = SendSmsCodeRequest{}
	mi := &file_public_v1_public_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsCodeRequest) ProtoMessage() {}

func (x *SendSmsCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_v1_public_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsCodeRequest.ProtoReflect.Descriptor instead.
func (*SendSmsCodeRequest) Descriptor() ([]byte, []int) {
	return file_public_v1_public_proto_rawDescGZIP(), []int{2}
}

func (x *SendSmsCodeRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SendSmsCodeRequest) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *SendSmsCodeRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

func (x *SendSmsCodeRequest) GetScene() SmsCodeScene {
	if x != nil {
		return x.Scene
	}
	return SmsCodeScene_UNSPECIFIED
}

type SendSmsCodeReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码过期时间戳（秒）
	ExpireAt      int64 `protobuf:"varint,1,opt,name=expire_at,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsCodeReply) Reset() {
	*x = SendSmsCodeReply{}
	mi := &file_public_v1_public_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsCodeReply) ProtoMessage() {}

func (x *SendSmsCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_public_v1_public_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsCodeReply.ProtoReflect.Descriptor instead.
func (*SendSmsCodeReply) Descriptor() ([]byte, []int) {
	return file_public_v1_public_proto_rawDescGZIP(), []int{3}
}

func (x *SendSmsCodeReply) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

var File_public_v1_public_proto protoreflect.FileDescriptor

const file_public_v1_public_proto_rawDesc = "" +
	"\n" +
	"\x16public/v1/public.proto\x12\rapi.public.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1copenapi/v3/annotations.proto\"\x13\n" +
	"\x11GetCaptchaRequest\"y\n" +
	"\x0fGetCaptchaReply\x121\n" +
	"\n" +
	"captcha_id\x18\x01 \x01(\tB\x11\xbaG\x0e\x92\x02\v验证码idR\n" +
	"captcha_id\x123\n" +
	"\timage_b64\x18\x02 \x01(\tB\x15\xbaG\x12\x92\x02\x0f验证码内容R\timage_b64\"\xbf\x02\n" +
	"\x12SendSmsCodeRequest\x12M\n" +
	"\x06mobile\x18\x01 \x01(\tB5\xe2A\x01\x02\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$\xbaG\x1a\x92\x02\x17手机号，11位数字R\x06mobile\x12;\n" +
	"\n" +
	"captcha_id\x18\x02 \x01(\tB\x1b\xe2A\x01\x02\xbaG\x14\x92\x02\x11图形验证码IDR\n" +
	"captcha_id\x129\n" +
	"\acaptcha\x18\x03 \x01(\tB\x1f\xe2A\x01\x02\xbaG\x18\x92\x02\x15图形验证码内容R\acaptcha\x12b\n" +
	"\x05scene\x18\x04 \x01(\x0e2\x1b.api.public.v1.SmsCodeSceneB/\xe2A\x01\x02\xfaB\a\x82\x01\x04\x10\x01 \x00\xbaG\x1e\x92\x02\x1b短信验证码业务场景R\x05scene\"\\\n" +
	"\x10SendSmsCodeReply\x12H\n" +
	"\texpire_at\x18\x01 \x01(\x03B*\xbaG'\x92\x02$验证码过期时间戳，单位秒R\texpire_at*N\n" +
	"\fSmsCodeScene\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LOGIN\x10\x01\x12\f\n" +
	"\bREGISTER\x10\x02\x12\n" +
	"\n" +
	"\x06FORGET\x10\x03\x12\b\n" +
	"\x04BIND\x10\x042\x97\x02\n" +
	"\x06Public\x12\x81\x01\n" +
	"\n" +
	"GetCaptcha\x12 .api.public.v1.GetCaptchaRequest\x1a\x1e.api.public.v1.GetCaptchaReply\"1\xbaG\x17\x12\x15获取图形验证码\x82\xd3\xe4\x93\x02\x11\x12\x0f/public/captcha\x12\x88\x01\n" +
	"\vSendSmsCode\x12!.api.public.v1.SendSmsCodeRequest\x1a\x1f.api.public.v1.SendSmsCodeReply\"5\xbaG\x17\x12\x15获取短信验证码\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/public/sms-codeBQ\n" +
	"\rapi.public.v1P\x01Z>github.com/sober-studio/bubble-boot-go-kratos/api/public/v1;v1b\x06proto3"

var (
	file_public_v1_public_proto_rawDescOnce sync.Once
	file_public_v1_public_proto_rawDescData []byte
)

func file_public_v1_public_proto_rawDescGZIP() []byte {
	file_public_v1_public_proto_rawDescOnce.Do(func() {
		file_public_v1_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_v1_public_proto_rawDesc), len(file_public_v1_public_proto_rawDesc)))
	})
	return file_public_v1_public_proto_rawDescData
}

var file_public_v1_public_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_public_v1_public_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_public_v1_public_proto_goTypes = []any{
	(SmsCodeScene)(0),          // 0: api.public.v1.SmsCodeScene
	(*GetCaptchaRequest)(nil),  // 1: api.public.v1.GetCaptchaRequest
	(*GetCaptchaReply)(nil),    // 2: api.public.v1.GetCaptchaReply
	(*SendSmsCodeRequest)(nil), // 3: api.public.v1.SendSmsCodeRequest
	(*SendSmsCodeReply)(nil),   // 4: api.public.v1.SendSmsCodeReply
}
var file_public_v1_public_proto_depIdxs = []int32{
	0, // 0: api.public.v1.SendSmsCodeRequest.scene:type_name -> api.public.v1.SmsCodeScene
	1, // 1: api.public.v1.Public.GetCaptcha:input_type -> api.public.v1.GetCaptchaRequest
	3, // 2: api.public.v1.Public.SendSmsCode:input_type -> api.public.v1.SendSmsCodeRequest
	2, // 3: api.public.v1.Public.GetCaptcha:output_type -> api.public.v1.GetCaptchaReply
	4, // 4: api.public.v1.Public.SendSmsCode:output_type -> api.public.v1.SendSmsCodeReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_public_v1_public_proto_init() }
func file_public_v1_public_proto_init() {
	if File_public_v1_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_v1_public_proto_rawDesc), len(file_public_v1_public_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_v1_public_proto_goTypes,
		DependencyIndexes: file_public_v1_public_proto_depIdxs,
		EnumInfos:         file_public_v1_public_proto_enumTypes,
		MessageInfos:      file_public_v1_public_proto_msgTypes,
	}.Build()
	File_public_v1_public_proto = out.File
	file_public_v1_public_proto_goTypes = nil
	file_public_v1_public_proto_depIdxs = nil
}
