// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: public/v1/public_error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicErrorReason int32

const (
	// 图形验证码生成错误
	PublicErrorReason_IMAGE_CAPTCHA_GENERATE_FAILED PublicErrorReason = 0
	// 图形验证码错误
	PublicErrorReason_IMAGE_CAPTCHA_VERIFY_FAILED PublicErrorReason = 1
	// 短信验证码场景错误
	PublicErrorReason_SMS_SCENE_INVALID PublicErrorReason = 2
	// 短信验证码发送过于频繁
	PublicErrorReason_SMS_SEND_TOO_FREQUENT PublicErrorReason = 3
	// 短信验证码发送异常
	PublicErrorReason_SMS_SENDER_ERROR PublicErrorReason = 4
	// 短信验证码错误
	PublicErrorReason_SMS_CODE_ERROR PublicErrorReason = 5
)

// Enum value maps for PublicErrorReason.
var (
	PublicErrorReason_name = map[int32]string{
		0: "IMAGE_CAPTCHA_GENERATE_FAILED",
		1: "IMAGE_CAPTCHA_VERIFY_FAILED",
		2: "SMS_SCENE_INVALID",
		3: "SMS_SEND_TOO_FREQUENT",
		4: "SMS_SENDER_ERROR",
		5: "SMS_CODE_ERROR",
	}
	PublicErrorReason_value = map[string]int32{
		"IMAGE_CAPTCHA_GENERATE_FAILED": 0,
		"IMAGE_CAPTCHA_VERIFY_FAILED":   1,
		"SMS_SCENE_INVALID":             2,
		"SMS_SEND_TOO_FREQUENT":         3,
		"SMS_SENDER_ERROR":              4,
		"SMS_CODE_ERROR":                5,
	}
)

func (x PublicErrorReason) Enum() *PublicErrorReason {
	p := new(PublicErrorReason)
	*p = x
	return p
}

func (x PublicErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_public_v1_public_error_reason_proto_enumTypes[0].Descriptor()
}

func (PublicErrorReason) Type() protoreflect.EnumType {
	return &file_public_v1_public_error_reason_proto_enumTypes[0]
}

func (x PublicErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublicErrorReason.Descriptor instead.
func (PublicErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_public_v1_public_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_public_v1_public_error_reason_proto protoreflect.FileDescriptor

const file_public_v1_public_error_reason_proto_rawDesc = "" +
	"\n" +
	"#public/v1/public_error_reason.proto\x12\rapi.public.v1\x1a\x13errors/errors.proto*\xb9\x01\n" +
	"\x11PublicErrorReason\x12!\n" +
	"\x1dIMAGE_CAPTCHA_GENERATE_FAILED\x10\x00\x12\x1f\n" +
	"\x1bIMAGE_CAPTCHA_VERIFY_FAILED\x10\x01\x12\x15\n" +
	"\x11SMS_SCENE_INVALID\x10\x02\x12\x19\n" +
	"\x15SMS_SEND_TOO_FREQUENT\x10\x03\x12\x14\n" +
	"\x10SMS_SENDER_ERROR\x10\x04\x12\x12\n" +
	"\x0eSMS_CODE_ERROR\x10\x05\x1a\x04\xa0E\x90\x03BQ\n" +
	"\rapi.public.v1P\x01Z>github.com/sober-studio/bubble-boot-go-kratos/api/public/v1;v1b\x06proto3"

var (
	file_public_v1_public_error_reason_proto_rawDescOnce sync.Once
	file_public_v1_public_error_reason_proto_rawDescData []byte
)

func file_public_v1_public_error_reason_proto_rawDescGZIP() []byte {
	file_public_v1_public_error_reason_proto_rawDescOnce.Do(func() {
		file_public_v1_public_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_v1_public_error_reason_proto_rawDesc), len(file_public_v1_public_error_reason_proto_rawDesc)))
	})
	return file_public_v1_public_error_reason_proto_rawDescData
}

var file_public_v1_public_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_public_v1_public_error_reason_proto_goTypes = []any{
	(PublicErrorReason)(0), // 0: api.public.v1.PublicErrorReason
}
var file_public_v1_public_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_public_v1_public_error_reason_proto_init() }
func file_public_v1_public_error_reason_proto_init() {
	if File_public_v1_public_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_v1_public_error_reason_proto_rawDesc), len(file_public_v1_public_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_v1_public_error_reason_proto_goTypes,
		DependencyIndexes: file_public_v1_public_error_reason_proto_depIdxs,
		EnumInfos:         file_public_v1_public_error_reason_proto_enumTypes,
	}.Build()
	File_public_v1_public_error_reason_proto = out.File
	file_public_v1_public_error_reason_proto_goTypes = nil
	file_public_v1_public_error_reason_proto_depIdxs = nil
}
