// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 图形验证码生成错误
func IsImageCaptchaGenerateFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PublicErrorReason_IMAGE_CAPTCHA_GENERATE_FAILED.String() && e.Code == 400
}

// 图形验证码生成错误
func ErrorImageCaptchaGenerateFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PublicErrorReason_IMAGE_CAPTCHA_GENERATE_FAILED.String(), fmt.Sprintf(format, args...))
}

// 图形验证码错误
func IsImageCaptchaVerifyFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PublicErrorReason_IMAGE_CAPTCHA_VERIFY_FAILED.String() && e.Code == 400
}

// 图形验证码错误
func ErrorImageCaptchaVerifyFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PublicErrorReason_IMAGE_CAPTCHA_VERIFY_FAILED.String(), fmt.Sprintf(format, args...))
}

// 短信验证码场景错误
func IsSmsSceneInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PublicErrorReason_SMS_SCENE_INVALID.String() && e.Code == 400
}

// 短信验证码场景错误
func ErrorSmsSceneInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PublicErrorReason_SMS_SCENE_INVALID.String(), fmt.Sprintf(format, args...))
}

// 短信验证码发送过于频繁
func IsSmsSendTooFrequent(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PublicErrorReason_SMS_SEND_TOO_FREQUENT.String() && e.Code == 400
}

// 短信验证码发送过于频繁
func ErrorSmsSendTooFrequent(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PublicErrorReason_SMS_SEND_TOO_FREQUENT.String(), fmt.Sprintf(format, args...))
}

// 短信验证码发送异常
func IsSmsSenderError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PublicErrorReason_SMS_SENDER_ERROR.String() && e.Code == 400
}

// 短信验证码发送异常
func ErrorSmsSenderError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PublicErrorReason_SMS_SENDER_ERROR.String(), fmt.Sprintf(format, args...))
}

// 短信验证码错误
func IsSmsCodeError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PublicErrorReason_SMS_CODE_ERROR.String() && e.Code == 400
}

// 短信验证码错误
func ErrorSmsCodeError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PublicErrorReason_SMS_CODE_ERROR.String(), fmt.Sprintf(format, args...))
}
