// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/public/v1/public.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 发送短信验证码 ==========
// 短信验证码场景
type SmsOtpScene int32

const (
	// 未指定（默认值，不应使用）
	SmsOtpScene_UNSPECIFIED SmsOtpScene = 0
	// 登录
	SmsOtpScene_LOGIN SmsOtpScene = 1
	// 注册
	SmsOtpScene_REGISTER SmsOtpScene = 2
	// 忘记密码
	SmsOtpScene_FORGET SmsOtpScene = 3
	// 绑定
	SmsOtpScene_BIND SmsOtpScene = 4
)

// Enum value maps for SmsOtpScene.
var (
	SmsOtpScene_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "LOGIN",
		2: "REGISTER",
		3: "FORGET",
		4: "BIND",
	}
	SmsOtpScene_value = map[string]int32{
		"UNSPECIFIED": 0,
		"LOGIN":       1,
		"REGISTER":    2,
		"FORGET":      3,
		"BIND":        4,
	}
)

func (x SmsOtpScene) Enum() *SmsOtpScene {
	p := new(SmsOtpScene)
	*p = x
	return p
}

func (x SmsOtpScene) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmsOtpScene) Descriptor() protoreflect.EnumDescriptor {
	return file_api_public_v1_public_proto_enumTypes[0].Descriptor()
}

func (SmsOtpScene) Type() protoreflect.EnumType {
	return &file_api_public_v1_public_proto_enumTypes[0]
}

func (x SmsOtpScene) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmsOtpScene.Descriptor instead.
func (SmsOtpScene) EnumDescriptor() ([]byte, []int) {
	return file_api_public_v1_public_proto_rawDescGZIP(), []int{0}
}

// ========== 获取图形验证码 ==========
type GetCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaRequest) Reset() {
	*x = GetCaptchaRequest{}
	mi := &file_api_public_v1_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaRequest) ProtoMessage() {}

func (x *GetCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_public_v1_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_api_public_v1_public_proto_rawDescGZIP(), []int{0}
}

type GetCaptchaReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码ID
	CaptchaId string `protobuf:"bytes,1,opt,name=captcha_id,proto3" json:"captcha_id,omitempty"`
	// Base64编码的图片
	ImageB64      string `protobuf:"bytes,2,opt,name=image_b64,proto3" json:"image_b64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaReply) Reset() {
	*x = GetCaptchaReply{}
	mi := &file_api_public_v1_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaReply) ProtoMessage() {}

func (x *GetCaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_public_v1_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaReply.ProtoReflect.Descriptor instead.
func (*GetCaptchaReply) Descriptor() ([]byte, []int) {
	return file_api_public_v1_public_proto_rawDescGZIP(), []int{1}
}

func (x *GetCaptchaReply) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *GetCaptchaReply) GetImageB64() string {
	if x != nil {
		return x.ImageB64
	}
	return ""
}

type SendSmsOtpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 手机号，规则：11位数字
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 图形验证码ID
	CaptchaId string `protobuf:"bytes,2,opt,name=captcha_id,proto3" json:"captcha_id,omitempty"`
	// 图形验证码
	Captcha string `protobuf:"bytes,3,opt,name=captcha,proto3" json:"captcha,omitempty"`
	// 验证码场景
	Scene         SmsOtpScene `protobuf:"varint,4,opt,name=scene,proto3,enum=api.public.v1.SmsOtpScene" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsOtpRequest) Reset() {
	*x = SendSmsOtpRequest{}
	mi := &file_api_public_v1_public_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsOtpRequest) ProtoMessage() {}

func (x *SendSmsOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_public_v1_public_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsOtpRequest.ProtoReflect.Descriptor instead.
func (*SendSmsOtpRequest) Descriptor() ([]byte, []int) {
	return file_api_public_v1_public_proto_rawDescGZIP(), []int{2}
}

func (x *SendSmsOtpRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SendSmsOtpRequest) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *SendSmsOtpRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

func (x *SendSmsOtpRequest) GetScene() SmsOtpScene {
	if x != nil {
		return x.Scene
	}
	return SmsOtpScene_UNSPECIFIED
}

type SendSmsOtpReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码过期时间戳（秒）
	ExpireAt      int64 `protobuf:"varint,1,opt,name=expire_at,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsOtpReply) Reset() {
	*x = SendSmsOtpReply{}
	mi := &file_api_public_v1_public_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsOtpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsOtpReply) ProtoMessage() {}

func (x *SendSmsOtpReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_public_v1_public_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsOtpReply.ProtoReflect.Descriptor instead.
func (*SendSmsOtpReply) Descriptor() ([]byte, []int) {
	return file_api_public_v1_public_proto_rawDescGZIP(), []int{3}
}

func (x *SendSmsOtpReply) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

var File_api_public_v1_public_proto protoreflect.FileDescriptor

const file_api_public_v1_public_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/public/v1/public.proto\x12\rapi.public.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1copenapi/v3/annotations.proto\"\x13\n" +
	"\x11GetCaptchaRequest\"y\n" +
	"\x0fGetCaptchaReply\x121\n" +
	"\n" +
	"captcha_id\x18\x01 \x01(\tB\x11\xbaG\x0e\x92\x02\v验证码idR\n" +
	"captcha_id\x123\n" +
	"\timage_b64\x18\x02 \x01(\tB\x15\xbaG\x12\x92\x02\x0f验证码内容R\timage_b64\"\xbd\x02\n" +
	"\x11SendSmsOtpRequest\x12M\n" +
	"\x06mobile\x18\x01 \x01(\tB5\xe2A\x01\x02\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$\xbaG\x1a\x92\x02\x17手机号，11位数字R\x06mobile\x12;\n" +
	"\n" +
	"captcha_id\x18\x02 \x01(\tB\x1b\xe2A\x01\x02\xbaG\x14\x92\x02\x11图形验证码IDR\n" +
	"captcha_id\x129\n" +
	"\acaptcha\x18\x03 \x01(\tB\x1f\xe2A\x01\x02\xbaG\x18\x92\x02\x15图形验证码内容R\acaptcha\x12a\n" +
	"\x05scene\x18\x04 \x01(\x0e2\x1a.api.public.v1.SmsOtpSceneB/\xe2A\x01\x02\xfaB\a\x82\x01\x04\x10\x01 \x00\xbaG\x1e\x92\x02\x1b短信验证码业务场景R\x05scene\"[\n" +
	"\x0fSendSmsOtpReply\x12H\n" +
	"\texpire_at\x18\x01 \x01(\x03B*\xbaG'\x92\x02$验证码过期时间戳，单位秒R\texpire_at*M\n" +
	"\vSmsOtpScene\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LOGIN\x10\x01\x12\f\n" +
	"\bREGISTER\x10\x02\x12\n" +
	"\n" +
	"\x06FORGET\x10\x03\x12\b\n" +
	"\x04BIND\x10\x042\x93\x02\n" +
	"\x06Public\x12\x81\x01\n" +
	"\n" +
	"GetCaptcha\x12 .api.public.v1.GetCaptchaRequest\x1a\x1e.api.public.v1.GetCaptchaReply\"1\xbaG\x17\x12\x15获取图形验证码\x82\xd3\xe4\x93\x02\x11\x12\x0f/public/captcha\x12\x84\x01\n" +
	"\n" +
	"SendSmsOtp\x12 .api.public.v1.SendSmsOtpRequest\x1a\x1e.api.public.v1.SendSmsOtpReply\"4\xbaG\x17\x12\x15获取短信验证码\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/public/otp/smsBQ\n" +
	"\rapi.public.v1P\x01Z>github.com/sober-studio/bubble-boot-go-kratos/api/public/v1;v1b\x06proto3"

var (
	file_api_public_v1_public_proto_rawDescOnce sync.Once
	file_api_public_v1_public_proto_rawDescData []byte
)

func file_api_public_v1_public_proto_rawDescGZIP() []byte {
	file_api_public_v1_public_proto_rawDescOnce.Do(func() {
		file_api_public_v1_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_public_v1_public_proto_rawDesc), len(file_api_public_v1_public_proto_rawDesc)))
	})
	return file_api_public_v1_public_proto_rawDescData
}

var file_api_public_v1_public_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_public_v1_public_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_public_v1_public_proto_goTypes = []any{
	(SmsOtpScene)(0),          // 0: api.public.v1.SmsOtpScene
	(*GetCaptchaRequest)(nil), // 1: api.public.v1.GetCaptchaRequest
	(*GetCaptchaReply)(nil),   // 2: api.public.v1.GetCaptchaReply
	(*SendSmsOtpRequest)(nil), // 3: api.public.v1.SendSmsOtpRequest
	(*SendSmsOtpReply)(nil),   // 4: api.public.v1.SendSmsOtpReply
}
var file_api_public_v1_public_proto_depIdxs = []int32{
	0, // 0: api.public.v1.SendSmsOtpRequest.scene:type_name -> api.public.v1.SmsOtpScene
	1, // 1: api.public.v1.Public.GetCaptcha:input_type -> api.public.v1.GetCaptchaRequest
	3, // 2: api.public.v1.Public.SendSmsOtp:input_type -> api.public.v1.SendSmsOtpRequest
	2, // 3: api.public.v1.Public.GetCaptcha:output_type -> api.public.v1.GetCaptchaReply
	4, // 4: api.public.v1.Public.SendSmsOtp:output_type -> api.public.v1.SendSmsOtpReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_public_v1_public_proto_init() }
func file_api_public_v1_public_proto_init() {
	if File_api_public_v1_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_public_v1_public_proto_rawDesc), len(file_api_public_v1_public_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_public_v1_public_proto_goTypes,
		DependencyIndexes: file_api_public_v1_public_proto_depIdxs,
		EnumInfos:         file_api_public_v1_public_proto_enumTypes,
		MessageInfos:      file_api_public_v1_public_proto_msgTypes,
	}.Build()
	File_api_public_v1_public_proto = out.File
	file_api_public_v1_public_proto_goTypes = nil
	file_api_public_v1_public_proto_depIdxs = nil
}
