// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: upload/v1/upload.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUploadUploadFile = "/api.upload.v1.Upload/UploadFile"

type UploadHTTPServer interface {
	// UploadFile 上传文件
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileReply, error)
}

func RegisterUploadHTTPServer(s *http.Server, srv UploadHTTPServer) {
	r := s.Route("/")
	r.POST("/upload", _Upload_UploadFile0_HTTP_Handler(srv))
}

func _Upload_UploadFile0_HTTP_Handler(srv UploadHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadFileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUploadUploadFile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadFile(ctx, req.(*UploadFileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadFileReply)
		return ctx.Result(200, reply)
	}
}

type UploadHTTPClient interface {
	// UploadFile 上传文件
	UploadFile(ctx context.Context, req *UploadFileRequest, opts ...http.CallOption) (rsp *UploadFileReply, err error)
}

type UploadHTTPClientImpl struct {
	cc *http.Client
}

func NewUploadHTTPClient(client *http.Client) UploadHTTPClient {
	return &UploadHTTPClientImpl{client}
}

// UploadFile 上传文件
func (c *UploadHTTPClientImpl) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...http.CallOption) (*UploadFileReply, error) {
	var out UploadFileReply
	pattern := "/upload"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUploadUploadFile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
