// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/upload/v1/upload.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 文件上传 ==========
// 上传场景枚举
type UploadScene int32

const (
	// 通用场景
	UploadScene_UPLOAD_COMMON UploadScene = 0
	// 用户头像
	UploadScene_UPLOAD_AVATAR UploadScene = 1
)

// Enum value maps for UploadScene.
var (
	UploadScene_name = map[int32]string{
		0: "UPLOAD_COMMON",
		1: "UPLOAD_AVATAR",
	}
	UploadScene_value = map[string]int32{
		"UPLOAD_COMMON": 0,
		"UPLOAD_AVATAR": 1,
	}
)

func (x UploadScene) Enum() *UploadScene {
	p := new(UploadScene)
	*p = x
	return p
}

func (x UploadScene) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadScene) Descriptor() protoreflect.EnumDescriptor {
	return file_api_upload_v1_upload_proto_enumTypes[0].Descriptor()
}

func (UploadScene) Type() protoreflect.EnumType {
	return &file_api_upload_v1_upload_proto_enumTypes[0]
}

func (x UploadScene) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadScene.Descriptor instead.
func (UploadScene) EnumDescriptor() ([]byte, []int) {
	return file_api_upload_v1_upload_proto_rawDescGZIP(), []int{0}
}

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 上传场景类型，用于区分不同的文件使用场景
	Scene UploadScene `protobuf:"varint,1,opt,name=scene,proto3,enum=api.upload.v1.UploadScene" json:"scene,omitempty"`
	// 文件数据（二进制格式），通过 multipart/form-data 上传
	File []byte `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	// 原始文件名（可选，用于保留文件扩展名）
	Filename      string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_api_upload_v1_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_upload_v1_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_upload_v1_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetScene() UploadScene {
	if x != nil {
		return x.Scene
	}
	return UploadScene_UPLOAD_COMMON
}

func (x *UploadFileRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UploadFileReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文件存储路径（对象存储的key）
	FileKey string `protobuf:"bytes,1,opt,name=file_key,proto3" json:"file_key,omitempty"`
	// 文件访问URL（公开文件直接返回URL，私有文件返回临时签名URL）
	FileUrl string `protobuf:"bytes,2,opt,name=file_url,proto3" json:"file_url,omitempty"`
	// 文件大小（字节）
	FileSize int64 `protobuf:"varint,3,opt,name=file_size,proto3" json:"file_size,omitempty"`
	// 是否为私有文件
	IsPrivate bool `protobuf:"varint,4,opt,name=is_private,proto3" json:"is_private,omitempty"`
	// 上传时间戳（秒）
	UploadedAt    int64 `protobuf:"varint,5,opt,name=uploaded_at,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileReply) Reset() {
	*x = UploadFileReply{}
	mi := &file_api_upload_v1_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileReply) ProtoMessage() {}

func (x *UploadFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_upload_v1_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileReply.ProtoReflect.Descriptor instead.
func (*UploadFileReply) Descriptor() ([]byte, []int) {
	return file_api_upload_v1_upload_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileReply) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *UploadFileReply) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UploadFileReply) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadFileReply) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *UploadFileReply) GetUploadedAt() int64 {
	if x != nil {
		return x.UploadedAt
	}
	return 0
}

var File_api_upload_v1_upload_proto protoreflect.FileDescriptor

const file_api_upload_v1_upload_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/upload/v1/upload.proto\x12\rapi.upload.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/httpbody.proto\x1a\x1copenapi/v3/annotations.proto\"\xf9\x02\n" +
	"\x11UploadFileRequest\x12\x95\x01\n" +
	"\x05scene\x18\x01 \x01(\x0e2\x1a.api.upload.v1.UploadSceneBc\xe2A\x01\x02\xfaB\x05\x82\x01\x02\x10\x01\xbaGT\x92\x02Q上传场景类型，必须为已定义的枚举值：UPLOAD_COMMON/UPLOAD_AVATARR\x05scene\x12f\n" +
	"\x04file\x18\x02 \x01(\fBR\xe2A\x01\x02\xbaGK\x92\x02?文件二进制数据，使用 multipart/form-data 格式上传\x9a\x02\x06binaryR\x04file\x12d\n" +
	"\bfilename\x18\x03 \x01(\tBH\xbaGE\x92\x02B原始文件名，用于获取文件扩展名，如：document.pdfR\bfilename\"\xd8\x03\n" +
	"\x0fUploadFileReply\x12O\n" +
	"\bfile_key\x18\x01 \x01(\tB3\xbaG0\x92\x02-文件在对象存储中的唯一标识路径R\bfile_key\x12q\n" +
	"\bfile_url\x18\x02 \x01(\tBU\xbaGR\x92\x02O文件访问地址，私有文件为临时签名URL（默认1小时有效期）R\bfile_url\x12H\n" +
	"\tfile_size\x18\x03 \x01(\x03B*\xbaG'\x92\x02$上传文件的大小，单位字节R\tfile_size\x12c\n" +
	"\n" +
	"is_private\x18\x04 \x01(\bBC\xbaG@\x92\x02=文件是否为私有访问，true表示需要签名URL访问R\n" +
	"is_private\x12R\n" +
	"\vuploaded_at\x18\x05 \x01(\x03B0\xbaG-\x92\x02*文件上传完成的时间戳，单位秒R\vuploaded_at*3\n" +
	"\vUploadScene\x12\x11\n" +
	"\rUPLOAD_COMMON\x10\x00\x12\x11\n" +
	"\rUPLOAD_AVATAR\x10\x012\xde\x01\n" +
	"\x06Upload\x12\xd3\x01\n" +
	"\n" +
	"UploadFile\x12 .api.upload.v1.UploadFileRequest\x1a\x1e.api.upload.v1.UploadFileReply\"\x82\x01\xbaGm\x12\f上传文件\x1a]支持多种场景的文件上传，根据场景类型自动配置存储路径和访问权限\x82\xd3\xe4\x93\x02\f:\x01*\"\a/uploadBQ\n" +
	"\rapi.upload.v1P\x01Z>github.com/sober-studio/bubble-boot-go-kratos/api/upload/v1;v1b\x06proto3"

var (
	file_api_upload_v1_upload_proto_rawDescOnce sync.Once
	file_api_upload_v1_upload_proto_rawDescData []byte
)

func file_api_upload_v1_upload_proto_rawDescGZIP() []byte {
	file_api_upload_v1_upload_proto_rawDescOnce.Do(func() {
		file_api_upload_v1_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_upload_v1_upload_proto_rawDesc), len(file_api_upload_v1_upload_proto_rawDesc)))
	})
	return file_api_upload_v1_upload_proto_rawDescData
}

var file_api_upload_v1_upload_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_upload_v1_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_upload_v1_upload_proto_goTypes = []any{
	(UploadScene)(0),          // 0: api.upload.v1.UploadScene
	(*UploadFileRequest)(nil), // 1: api.upload.v1.UploadFileRequest
	(*UploadFileReply)(nil),   // 2: api.upload.v1.UploadFileReply
}
var file_api_upload_v1_upload_proto_depIdxs = []int32{
	0, // 0: api.upload.v1.UploadFileRequest.scene:type_name -> api.upload.v1.UploadScene
	1, // 1: api.upload.v1.Upload.UploadFile:input_type -> api.upload.v1.UploadFileRequest
	2, // 2: api.upload.v1.Upload.UploadFile:output_type -> api.upload.v1.UploadFileReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_upload_v1_upload_proto_init() }
func file_api_upload_v1_upload_proto_init() {
	if File_api_upload_v1_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_upload_v1_upload_proto_rawDesc), len(file_api_upload_v1_upload_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_upload_v1_upload_proto_goTypes,
		DependencyIndexes: file_api_upload_v1_upload_proto_depIdxs,
		EnumInfos:         file_api_upload_v1_upload_proto_enumTypes,
		MessageInfos:      file_api_upload_v1_upload_proto_msgTypes,
	}.Build()
	File_api_upload_v1_upload_proto = out.File
	file_api_upload_v1_upload_proto_goTypes = nil
	file_api_upload_v1_upload_proto_depIdxs = nil
}
