// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/biz"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/conf"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/data"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/pkg/auth"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/pkg/email"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/pkg/sms"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/server"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, app *conf.App, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	db := data.NewDB(confData, logger)
	client := data.NewRedis(confData, logger)
	idGenerator := data.NewIDGenerator(app)
	dataData, cleanup, err := data.NewData(confData, logger, db, client, idGenerator)
	if err != nil {
		return nil, nil, err
	}
	store := data.NewRedisCaptchaStore(dataData)
	captchaUseCase := biz.NewCaptchaUseCase(store, logger)
	sender := sms.NewSmsSender(confData, logger)
	emailSender := email.NewEmailSender(confData, logger)
	otpCache := data.NewRedisOtpCache(dataData)
	otpUseCase := biz.NewOtpUseCase(sender, emailSender, otpCache, app, logger)
	tokenStore := auth.NewTokenStore(app, client)
	tokenService := auth.NewTokenService(app, tokenStore)
	userRepo := data.NewUserRepo(dataData, logger)
	passportUseCase := biz.NewPassportUseCase(tokenService, userRepo, app, logger)
	publicService := service.NewPublicService(captchaUseCase, otpUseCase, passportUseCase, logger)
	passportService := service.NewPassportService(passportUseCase, otpUseCase, captchaUseCase)
	httpServer := server.NewHTTPServer(confServer, app, publicService, passportService, tokenService, logger)
	kratosApp := newApp(logger, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup()
	}, nil
}
