// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/conf"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/data"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/pkg/auth"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/server"
	"github.com/sober-studio/bubble-boot-go-kratos/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, app *conf.App, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	publicService := service.NewPublicService()
	passportService := service.NewPassportService()
	client := data.NewRedis(confData, logger)
	tokenStore := auth.NewTokenStore(app, client)
	tokenService := auth.NewTokenService(app, tokenStore)
	httpServer := server.NewHTTPServer(confServer, app, publicService, passportService, tokenService, logger)
	kratosApp := newApp(logger, grpcServer, httpServer)
	return kratosApp, func() {
	}, nil
}
