// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	App           *App                   `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Sms           *Data_Sms              `protobuf:"bytes,3,opt,name=sms,proto3" json:"sms,omitempty"`
	Email         *Data_Email            `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetSms() *Data_Sms {
	if x != nil {
		return x.Sms
	}
	return nil
}

func (x *Data) GetEmail() *Data_Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *App_Auth              `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	WorkerId      int64                  `protobuf:"varint,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Otp           *App_Otp               `protobuf:"bytes,4,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *App) GetAuth() *App_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *App) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *App) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *App) GetOtp() *App_Otp {
	if x != nil {
		return x.Otp
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Driver string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// 连接池配置
	MaxIdleConns    int32                `protobuf:"varint,3,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxOpenConns    int32                `protobuf:"varint,4,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	ConnMaxLifetime *durationpb.Duration `protobuf:"bytes,5,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_Database) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_Database) GetConnMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return nil
}

type Data_Redis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 移除 network 字段
	Addr          string               `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	Password      string               `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Database      int32                `protobuf:"varint,7,opt,name=database,proto3" json:"database,omitempty"`
	PoolSize      int32                `protobuf:"varint,8,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDatabase() int32 {
	if x != nil {
		return x.Database
	}
	return 0
}

func (x *Data_Redis) GetPoolSize() int32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

type Data_Sms struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Provider        string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                                                                                                                // aliyun, tencent
	TemplateMapping map[string]string      `protobuf:"bytes,2,rep,name=template_mapping,json=templateMapping,proto3" json:"template_mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // "otp_login" -> "SMS_123"
	AccessKey       string                 `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	AccessSecret    string                 `protobuf:"bytes,4,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	SignName        string                 `protobuf:"bytes,5,opt,name=sign_name,json=signName,proto3" json:"sign_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_Sms) Reset() {
	*x = Data_Sms{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Sms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Sms) ProtoMessage() {}

func (x *Data_Sms) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Sms.ProtoReflect.Descriptor instead.
func (*Data_Sms) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Data_Sms) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Data_Sms) GetTemplateMapping() map[string]string {
	if x != nil {
		return x.TemplateMapping
	}
	return nil
}

func (x *Data_Sms) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Data_Sms) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

func (x *Data_Sms) GetSignName() string {
	if x != nil {
		return x.SignName
	}
	return ""
}

type Data_Email struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	From           string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Smtp           *Data_Email_SMTP       `protobuf:"bytes,2,opt,name=smtp,proto3" json:"smtp,omitempty"`
	SubjectMapping map[string]string      `protobuf:"bytes,3,rep,name=subject_mapping,json=subjectMapping,proto3" json:"subject_mapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // "otp_bind" -> "绑定验证码"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Data_Email) Reset() {
	*x = Data_Email{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Email) ProtoMessage() {}

func (x *Data_Email) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Email.ProtoReflect.Descriptor instead.
func (*Data_Email) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Data_Email) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Data_Email) GetSmtp() *Data_Email_SMTP {
	if x != nil {
		return x.Smtp
	}
	return nil
}

func (x *Data_Email) GetSubjectMapping() map[string]string {
	if x != nil {
		return x.SubjectMapping
	}
	return nil
}

type Data_Email_SMTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Email_SMTP) Reset() {
	*x = Data_Email_SMTP{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Email_SMTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Email_SMTP) ProtoMessage() {}

func (x *Data_Email_SMTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Email_SMTP.ProtoReflect.Descriptor instead.
func (*Data_Email_SMTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 3, 0}
}

func (x *Data_Email_SMTP) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Data_Email_SMTP) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Data_Email_SMTP) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_Email_SMTP) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type App_Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicPaths   []string               `protobuf:"bytes,1,rep,name=public_paths,json=publicPaths,proto3" json:"public_paths,omitempty"`
	Passport      *App_Auth_Passport     `protobuf:"bytes,2,opt,name=passport,proto3" json:"passport,omitempty"`
	Jwt           *App_Auth_JWT          `protobuf:"bytes,3,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App_Auth) Reset() {
	*x = App_Auth{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App_Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Auth) ProtoMessage() {}

func (x *App_Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Auth.ProtoReflect.Descriptor instead.
func (*App_Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *App_Auth) GetPublicPaths() []string {
	if x != nil {
		return x.PublicPaths
	}
	return nil
}

func (x *App_Auth) GetPassport() *App_Auth_Passport {
	if x != nil {
		return x.Passport
	}
	return nil
}

func (x *App_Auth) GetJwt() *App_Auth_JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type App_Otp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	PhoneScenes   map[string]*App_Otp_Scene `protobuf:"bytes,1,rep,name=phone_scenes,json=phoneScenes,proto3" json:"phone_scenes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 手机号场景
	EmailScenes   map[string]*App_Otp_Scene `protobuf:"bytes,2,rep,name=email_scenes,json=emailScenes,proto3" json:"email_scenes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 邮箱场景
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App_Otp) Reset() {
	*x = App_Otp{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App_Otp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Otp) ProtoMessage() {}

func (x *App_Otp) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Otp.ProtoReflect.Descriptor instead.
func (*App_Otp) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *App_Otp) GetPhoneScenes() map[string]*App_Otp_Scene {
	if x != nil {
		return x.PhoneScenes
	}
	return nil
}

func (x *App_Otp) GetEmailScenes() map[string]*App_Otp_Scene {
	if x != nil {
		return x.EmailScenes
	}
	return nil
}

type App_Auth_Passport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AutoRegister  bool                   `protobuf:"varint,1,opt,name=auto_register,json=autoRegister,proto3" json:"auto_register,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App_Auth_Passport) Reset() {
	*x = App_Auth_Passport{}
	mi := &file_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App_Auth_Passport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Auth_Passport) ProtoMessage() {}

func (x *App_Auth_Passport) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Auth_Passport.ProtoReflect.Descriptor instead.
func (*App_Auth_Passport) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *App_Auth_Passport) GetAutoRegister() bool {
	if x != nil {
		return x.AutoRegister
	}
	return false
}

type App_Auth_JWT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Store         string                 `protobuf:"bytes,2,opt,name=store,proto3" json:"store,omitempty"`
	Expire        int64                  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App_Auth_JWT) Reset() {
	*x = App_Auth_JWT{}
	mi := &file_conf_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App_Auth_JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Auth_JWT) ProtoMessage() {}

func (x *App_Auth_JWT) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Auth_JWT.ProtoReflect.Descriptor instead.
func (*App_Auth_JWT) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 0, 1}
}

func (x *App_Auth_JWT) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *App_Auth_JWT) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *App_Auth_JWT) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

type App_Otp_Scene struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpiresIn      *durationpb.Duration   `protobuf:"bytes,1,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`                // 有效期(秒)
	ResendInterval *durationpb.Duration   `protobuf:"bytes,2,opt,name=resend_interval,json=resendInterval,proto3" json:"resend_interval,omitempty"` // 重发间隔(秒)
	TemplateName   string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`       // 业务逻辑模板名
	CodeLength     int32                  `protobuf:"varint,4,opt,name=code_length,json=codeLength,proto3" json:"code_length,omitempty"`            // 验证码长度
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *App_Otp_Scene) Reset() {
	*x = App_Otp_Scene{}
	mi := &file_conf_conf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App_Otp_Scene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App_Otp_Scene) ProtoMessage() {}

func (x *App_Otp_Scene) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App_Otp_Scene.ProtoReflect.Descriptor instead.
func (*App_Otp_Scene) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3, 1, 0}
}

func (x *App_Otp_Scene) GetExpiresIn() *durationpb.Duration {
	if x != nil {
		return x.ExpiresIn
	}
	return nil
}

func (x *App_Otp_Scene) GetResendInterval() *durationpb.Duration {
	if x != nil {
		return x.ResendInterval
	}
	return nil
}

func (x *App_Otp_Scene) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *App_Otp_Scene) GetCodeLength() int32 {
	if x != nil {
		return x.CodeLength
	}
	return 0
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\x80\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12!\n" +
	"\x03app\x18\x03 \x01(\v2\x0f.kratos.api.AppR\x03app\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xf0\t\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x12&\n" +
	"\x03sms\x18\x03 \x01(\v2\x14.kratos.api.Data.SmsR\x03sms\x12,\n" +
	"\x05email\x18\x04 \x01(\v2\x16.kratos.api.Data.EmailR\x05email\x1a\xcd\x01\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12$\n" +
	"\x0emax_idle_conns\x18\x03 \x01(\x05R\fmaxIdleConns\x12$\n" +
	"\x0emax_open_conns\x18\x04 \x01(\x05R\fmaxOpenConns\x12E\n" +
	"\x11conn_max_lifetime\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxLifetime\x1a\xee\x01\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\a \x01(\x05R\bdatabase\x12\x1b\n" +
	"\tpool_size\x18\b \x01(\x05R\bpoolSize\x1a\x9c\x02\n" +
	"\x03Sms\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12T\n" +
	"\x10template_mapping\x18\x02 \x03(\v2).kratos.api.Data.Sms.TemplateMappingEntryR\x0ftemplateMapping\x12\x1d\n" +
	"\n" +
	"access_key\x18\x03 \x01(\tR\taccessKey\x12#\n" +
	"\raccess_secret\x18\x04 \x01(\tR\faccessSecret\x12\x1b\n" +
	"\tsign_name\x18\x05 \x01(\tR\bsignName\x1aB\n" +
	"\x14TemplateMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xcc\x02\n" +
	"\x05Email\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12/\n" +
	"\x04smtp\x18\x02 \x01(\v2\x1b.kratos.api.Data.Email.SMTPR\x04smtp\x12S\n" +
	"\x0fsubject_mapping\x18\x03 \x03(\v2*.kratos.api.Data.Email.SubjectMappingEntryR\x0esubjectMapping\x1af\n" +
	"\x04SMTP\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x1aA\n" +
	"\x13SubjectMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\a\n" +
	"\x03App\x12(\n" +
	"\x04auth\x18\x01 \x01(\v2\x14.kratos.api.App.AuthR\x04auth\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\x03R\bworkerId\x12%\n" +
	"\x03otp\x18\x04 \x01(\v2\x13.kratos.api.App.OtpR\x03otp\x1a\x8e\x02\n" +
	"\x04Auth\x12!\n" +
	"\fpublic_paths\x18\x01 \x03(\tR\vpublicPaths\x129\n" +
	"\bpassport\x18\x02 \x01(\v2\x1d.kratos.api.App.Auth.PassportR\bpassport\x12*\n" +
	"\x03jwt\x18\x03 \x01(\v2\x18.kratos.api.App.Auth.JWTR\x03jwt\x1a/\n" +
	"\bPassport\x12#\n" +
	"\rauto_register\x18\x01 \x01(\bR\fautoRegister\x1aK\n" +
	"\x03JWT\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x14\n" +
	"\x05store\x18\x02 \x01(\tR\x05store\x12\x16\n" +
	"\x06expire\x18\x03 \x01(\x03R\x06expire\x1a\x9b\x04\n" +
	"\x03Otp\x12G\n" +
	"\fphone_scenes\x18\x01 \x03(\v2$.kratos.api.App.Otp.PhoneScenesEntryR\vphoneScenes\x12G\n" +
	"\femail_scenes\x18\x02 \x03(\v2$.kratos.api.App.Otp.EmailScenesEntryR\vemailScenes\x1a\xcb\x01\n" +
	"\x05Scene\x128\n" +
	"\n" +
	"expires_in\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\texpiresIn\x12B\n" +
	"\x0fresend_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0eresendInterval\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12\x1f\n" +
	"\vcode_length\x18\x04 \x01(\x05R\n" +
	"codeLength\x1aY\n" +
	"\x10PhoneScenesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.kratos.api.App.Otp.SceneR\x05value:\x028\x01\x1aY\n" +
	"\x10EmailScenesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.kratos.api.App.Otp.SceneR\x05value:\x028\x01B*Z(bubble-boot-go-kratos/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*App)(nil),                 // 3: kratos.api.App
	(*Server_HTTP)(nil),         // 4: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 5: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 6: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 7: kratos.api.Data.Redis
	(*Data_Sms)(nil),            // 8: kratos.api.Data.Sms
	(*Data_Email)(nil),          // 9: kratos.api.Data.Email
	nil,                         // 10: kratos.api.Data.Sms.TemplateMappingEntry
	(*Data_Email_SMTP)(nil),     // 11: kratos.api.Data.Email.SMTP
	nil,                         // 12: kratos.api.Data.Email.SubjectMappingEntry
	(*App_Auth)(nil),            // 13: kratos.api.App.Auth
	(*App_Otp)(nil),             // 14: kratos.api.App.Otp
	(*App_Auth_Passport)(nil),   // 15: kratos.api.App.Auth.Passport
	(*App_Auth_JWT)(nil),        // 16: kratos.api.App.Auth.JWT
	(*App_Otp_Scene)(nil),       // 17: kratos.api.App.Otp.Scene
	nil,                         // 18: kratos.api.App.Otp.PhoneScenesEntry
	nil,                         // 19: kratos.api.App.Otp.EmailScenesEntry
	(*durationpb.Duration)(nil), // 20: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.app:type_name -> kratos.api.App
	4,  // 3: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	5,  // 4: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	6,  // 5: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	7,  // 6: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	8,  // 7: kratos.api.Data.sms:type_name -> kratos.api.Data.Sms
	9,  // 8: kratos.api.Data.email:type_name -> kratos.api.Data.Email
	13, // 9: kratos.api.App.auth:type_name -> kratos.api.App.Auth
	14, // 10: kratos.api.App.otp:type_name -> kratos.api.App.Otp
	20, // 11: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	20, // 12: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	20, // 13: kratos.api.Data.Database.conn_max_lifetime:type_name -> google.protobuf.Duration
	20, // 14: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	20, // 15: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	10, // 16: kratos.api.Data.Sms.template_mapping:type_name -> kratos.api.Data.Sms.TemplateMappingEntry
	11, // 17: kratos.api.Data.Email.smtp:type_name -> kratos.api.Data.Email.SMTP
	12, // 18: kratos.api.Data.Email.subject_mapping:type_name -> kratos.api.Data.Email.SubjectMappingEntry
	15, // 19: kratos.api.App.Auth.passport:type_name -> kratos.api.App.Auth.Passport
	16, // 20: kratos.api.App.Auth.jwt:type_name -> kratos.api.App.Auth.JWT
	18, // 21: kratos.api.App.Otp.phone_scenes:type_name -> kratos.api.App.Otp.PhoneScenesEntry
	19, // 22: kratos.api.App.Otp.email_scenes:type_name -> kratos.api.App.Otp.EmailScenesEntry
	20, // 23: kratos.api.App.Otp.Scene.expires_in:type_name -> google.protobuf.Duration
	20, // 24: kratos.api.App.Otp.Scene.resend_interval:type_name -> google.protobuf.Duration
	17, // 25: kratos.api.App.Otp.PhoneScenesEntry.value:type_name -> kratos.api.App.Otp.Scene
	17, // 26: kratos.api.App.Otp.EmailScenesEntry.value:type_name -> kratos.api.App.Otp.Scene
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
