// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	Username     string  `gorm:"column:username;type:character varying(255);not null;comment:用户名" json:"username"`            // 用户名
	PasswordHash string  `gorm:"column:password_hash;type:character varying(255);not null;comment:密码哈希" json:"password_hash"` // 密码哈希
	Phone        *string `gorm:"column:phone;type:character varying(20);comment:手机号" json:"phone"`                            // 手机号
	Nickname     *string `gorm:"column:nickname;type:character varying(100);comment:昵称" json:"nickname"`                      // 昵称
	IsAvailable  *bool   `gorm:"column:is_available;type:boolean;comment:是否可用" json:"is_available"`                           // 是否可用
	BaseModel    `gorm:"embedded"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
