// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsRegisterFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_REGISTER_FAILED.String() && e.Code == 400
}

func ErrorRegisterFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_REGISTER_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsLoginFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_LOGIN_FAILED.String() && e.Code == 400
}

func ErrorLoginFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_LOGIN_FAILED.String(), fmt.Sprintf(format, args...))
}

// 手机号已经被注册
func IsPhoneAlreadyRegistered(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_PHONE_ALREADY_REGISTERED.String() && e.Code == 400
}

// 手机号已经被注册
func ErrorPhoneAlreadyRegistered(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_PHONE_ALREADY_REGISTERED.String(), fmt.Sprintf(format, args...))
}

// 身份证号已经被注册
func IsIdCardAlreadyRegistered(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_ID_CARD_ALREADY_REGISTERED.String() && e.Code == 400
}

// 身份证号已经被注册
func ErrorIdCardAlreadyRegistered(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_ID_CARD_ALREADY_REGISTERED.String(), fmt.Sprintf(format, args...))
}

// 用户名或密码错误
func IsUsernameOrPasswordError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_USERNAME_OR_PASSWORD_ERROR.String() && e.Code == 400
}

// 用户名或密码错误
func ErrorUsernameOrPasswordError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_USERNAME_OR_PASSWORD_ERROR.String(), fmt.Sprintf(format, args...))
}

// 用户被禁用
func IsUserDisabled(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_USER_DISABLED.String() && e.Code == 400
}

// 用户被禁用
func ErrorUserDisabled(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_USER_DISABLED.String(), fmt.Sprintf(format, args...))
}

// 用户被加入黑名单
func IsUserBlacklisted(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_USER_BLACKLISTED.String() && e.Code == 400
}

// 用户被加入黑名单
func ErrorUserBlacklisted(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_USER_BLACKLISTED.String(), fmt.Sprintf(format, args...))
}

// 用户不存在
func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_USER_NOT_FOUND.String() && e.Code == 400
}

// 用户不存在
func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 注销失败
func IsLogoutFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_LOGOUT_FAILED.String() && e.Code == 400
}

// 注销失败
func ErrorLogoutFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_LOGOUT_FAILED.String(), fmt.Sprintf(format, args...))
}

// 两次密码不一致
func IsPasswordNotMatch(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_PASSWORD_NOT_MATCH.String() && e.Code == 400
}

// 两次密码不一致
func ErrorPasswordNotMatch(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_PASSWORD_NOT_MATCH.String(), fmt.Sprintf(format, args...))
}

// 重置密码失败
func IsResetPasswordFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == PassportErrorReason_RESET_PASSWORD_FAILED.String() && e.Code == 400
}

// 重置密码失败
func ErrorResetPasswordFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, PassportErrorReason_RESET_PASSWORD_FAILED.String(), fmt.Sprintf(format, args...))
}
