// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: passport/v1/passport_error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PassportErrorReason int32

const (
	PassportErrorReason_REGISTER_FAILED PassportErrorReason = 0
	PassportErrorReason_LOGIN_FAILED    PassportErrorReason = 1
	// 手机号已经被注册
	PassportErrorReason_PHONE_ALREADY_REGISTERED PassportErrorReason = 2
	// 身份证号已经被注册
	PassportErrorReason_ID_CARD_ALREADY_REGISTERED PassportErrorReason = 3
	// 用户名或密码错误
	PassportErrorReason_USERNAME_OR_PASSWORD_ERROR PassportErrorReason = 4
	// 用户被禁用
	PassportErrorReason_USER_DISABLED PassportErrorReason = 5
	// 用户被加入黑名单
	PassportErrorReason_USER_BLACKLISTED PassportErrorReason = 6
	// 用户不存在
	PassportErrorReason_USER_NOT_FOUND PassportErrorReason = 7
	// 注销失败
	PassportErrorReason_LOGOUT_FAILED PassportErrorReason = 8
	// 两次密码不一致
	PassportErrorReason_PASSWORD_NOT_MATCH PassportErrorReason = 9
	// 重置密码失败
	PassportErrorReason_RESET_PASSWORD_FAILED PassportErrorReason = 10
)

// Enum value maps for PassportErrorReason.
var (
	PassportErrorReason_name = map[int32]string{
		0:  "REGISTER_FAILED",
		1:  "LOGIN_FAILED",
		2:  "PHONE_ALREADY_REGISTERED",
		3:  "ID_CARD_ALREADY_REGISTERED",
		4:  "USERNAME_OR_PASSWORD_ERROR",
		5:  "USER_DISABLED",
		6:  "USER_BLACKLISTED",
		7:  "USER_NOT_FOUND",
		8:  "LOGOUT_FAILED",
		9:  "PASSWORD_NOT_MATCH",
		10: "RESET_PASSWORD_FAILED",
	}
	PassportErrorReason_value = map[string]int32{
		"REGISTER_FAILED":            0,
		"LOGIN_FAILED":               1,
		"PHONE_ALREADY_REGISTERED":   2,
		"ID_CARD_ALREADY_REGISTERED": 3,
		"USERNAME_OR_PASSWORD_ERROR": 4,
		"USER_DISABLED":              5,
		"USER_BLACKLISTED":           6,
		"USER_NOT_FOUND":             7,
		"LOGOUT_FAILED":              8,
		"PASSWORD_NOT_MATCH":         9,
		"RESET_PASSWORD_FAILED":      10,
	}
)

func (x PassportErrorReason) Enum() *PassportErrorReason {
	p := new(PassportErrorReason)
	*p = x
	return p
}

func (x PassportErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PassportErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_passport_v1_passport_error_reason_proto_enumTypes[0].Descriptor()
}

func (PassportErrorReason) Type() protoreflect.EnumType {
	return &file_passport_v1_passport_error_reason_proto_enumTypes[0]
}

func (x PassportErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PassportErrorReason.Descriptor instead.
func (PassportErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_passport_v1_passport_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_passport_v1_passport_error_reason_proto protoreflect.FileDescriptor

const file_passport_v1_passport_error_reason_proto_rawDesc = "" +
	"\n" +
	"'passport/v1/passport_error_reason.proto\x12\x0fapi.passport.v1\x1a\x13errors/errors.proto*\xa3\x02\n" +
	"\x13PassportErrorReason\x12\x13\n" +
	"\x0fREGISTER_FAILED\x10\x00\x12\x10\n" +
	"\fLOGIN_FAILED\x10\x01\x12\x1c\n" +
	"\x18PHONE_ALREADY_REGISTERED\x10\x02\x12\x1e\n" +
	"\x1aID_CARD_ALREADY_REGISTERED\x10\x03\x12\x1e\n" +
	"\x1aUSERNAME_OR_PASSWORD_ERROR\x10\x04\x12\x11\n" +
	"\rUSER_DISABLED\x10\x05\x12\x14\n" +
	"\x10USER_BLACKLISTED\x10\x06\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\a\x12\x11\n" +
	"\rLOGOUT_FAILED\x10\b\x12\x16\n" +
	"\x12PASSWORD_NOT_MATCH\x10\t\x12\x19\n" +
	"\x15RESET_PASSWORD_FAILED\x10\n" +
	"\x1a\x04\xa0E\x90\x03BU\n" +
	"\x0fapi.passport.v1P\x01Z@github.com/sober-studio/bubble-boot-go-kratos/api/passport/v1;v1b\x06proto3"

var (
	file_passport_v1_passport_error_reason_proto_rawDescOnce sync.Once
	file_passport_v1_passport_error_reason_proto_rawDescData []byte
)

func file_passport_v1_passport_error_reason_proto_rawDescGZIP() []byte {
	file_passport_v1_passport_error_reason_proto_rawDescOnce.Do(func() {
		file_passport_v1_passport_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_passport_v1_passport_error_reason_proto_rawDesc), len(file_passport_v1_passport_error_reason_proto_rawDesc)))
	})
	return file_passport_v1_passport_error_reason_proto_rawDescData
}

var file_passport_v1_passport_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_passport_v1_passport_error_reason_proto_goTypes = []any{
	(PassportErrorReason)(0), // 0: api.passport.v1.PassportErrorReason
}
var file_passport_v1_passport_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_passport_v1_passport_error_reason_proto_init() }
func file_passport_v1_passport_error_reason_proto_init() {
	if File_passport_v1_passport_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_passport_v1_passport_error_reason_proto_rawDesc), len(file_passport_v1_passport_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_passport_v1_passport_error_reason_proto_goTypes,
		DependencyIndexes: file_passport_v1_passport_error_reason_proto_depIdxs,
		EnumInfos:         file_passport_v1_passport_error_reason_proto_enumTypes,
	}.Build()
	File_passport_v1_passport_error_reason_proto = out.File
	file_passport_v1_passport_error_reason_proto_goTypes = nil
	file_passport_v1_passport_error_reason_proto_depIdxs = nil
}
