// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: passport/v1/passport.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPassportBindMobile = "/api.passport.v1.Passport/BindMobile"
const OperationPassportLoginByOtp = "/api.passport.v1.Passport/LoginByOtp"
const OperationPassportLoginByPassword = "/api.passport.v1.Passport/LoginByPassword"
const OperationPassportLogout = "/api.passport.v1.Passport/Logout"
const OperationPassportRegister = "/api.passport.v1.Passport/Register"
const OperationPassportResetPassword = "/api.passport.v1.Passport/ResetPassword"
const OperationPassportUpdateMobile = "/api.passport.v1.Passport/UpdateMobile"
const OperationPassportUpdatePassword = "/api.passport.v1.Passport/UpdatePassword"
const OperationPassportUserInfo = "/api.passport.v1.Passport/UserInfo"

type PassportHTTPServer interface {
	// BindMobile 绑定手机号
	BindMobile(context.Context, *BindMobileRequest) (*BindMobileReply, error)
	// LoginByOtp 验证码登录
	LoginByOtp(context.Context, *LoginByOtpRequest) (*LoginReply, error)
	// LoginByPassword 密码登录
	LoginByPassword(context.Context, *LoginByPasswordRequest) (*LoginReply, error)
	// Logout 用户退出
	Logout(context.Context, *LogoutRequest) (*LogoutReply, error)
	// Register 用户注册
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	// ResetPassword 找回密码
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordReply, error)
	// UpdateMobile 修改绑定手机号
	UpdateMobile(context.Context, *UpdateMobileRequest) (*UpdateMobileReply, error)
	// UpdatePassword 修改密码
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*UpdatePasswordReply, error)
	// UserInfo 获取用户信息
	UserInfo(context.Context, *UserInfoRequest) (*UserInfoReply, error)
}

func RegisterPassportHTTPServer(s *http.Server, srv PassportHTTPServer) {
	r := s.Route("/")
	r.POST("/passport/register", _Passport_Register0_HTTP_Handler(srv))
	r.POST("/passport/login/password", _Passport_LoginByPassword0_HTTP_Handler(srv))
	r.POST("/passport/login/otp", _Passport_LoginByOtp0_HTTP_Handler(srv))
	r.POST("/passport/logout", _Passport_Logout0_HTTP_Handler(srv))
	r.GET("/passport/user-info", _Passport_UserInfo0_HTTP_Handler(srv))
	r.POST("/passport/update-password", _Passport_UpdatePassword0_HTTP_Handler(srv))
	r.POST("/passport/bind-mobile", _Passport_BindMobile0_HTTP_Handler(srv))
	r.POST("/passport/update-mobile", _Passport_UpdateMobile0_HTTP_Handler(srv))
	r.POST("/passport/reset-password", _Passport_ResetPassword0_HTTP_Handler(srv))
}

func _Passport_Register0_HTTP_Handler(srv PassportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassportRegister)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Register(ctx, req.(*RegisterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterReply)
		return ctx.Result(200, reply)
	}
}

func _Passport_LoginByPassword0_HTTP_Handler(srv PassportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginByPasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassportLoginByPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginByPassword(ctx, req.(*LoginByPasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _Passport_LoginByOtp0_HTTP_Handler(srv PassportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginByOtpRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassportLoginByOtp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginByOtp(ctx, req.(*LoginByOtpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _Passport_Logout0_HTTP_Handler(srv PassportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassportLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutReply)
		return ctx.Result(200, reply)
	}
}

func _Passport_UserInfo0_HTTP_Handler(srv PassportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassportUserInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UserInfo(ctx, req.(*UserInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserInfoReply)
		return ctx.Result(200, reply)
	}
}

func _Passport_UpdatePassword0_HTTP_Handler(srv PassportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassportUpdatePassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePassword(ctx, req.(*UpdatePasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePasswordReply)
		return ctx.Result(200, reply)
	}
}

func _Passport_BindMobile0_HTTP_Handler(srv PassportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindMobileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassportBindMobile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindMobile(ctx, req.(*BindMobileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BindMobileReply)
		return ctx.Result(200, reply)
	}
}

func _Passport_UpdateMobile0_HTTP_Handler(srv PassportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMobileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassportUpdateMobile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMobile(ctx, req.(*UpdateMobileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateMobileReply)
		return ctx.Result(200, reply)
	}
}

func _Passport_ResetPassword0_HTTP_Handler(srv PassportHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResetPasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPassportResetPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResetPassword(ctx, req.(*ResetPasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResetPasswordReply)
		return ctx.Result(200, reply)
	}
}

type PassportHTTPClient interface {
	// BindMobile 绑定手机号
	BindMobile(ctx context.Context, req *BindMobileRequest, opts ...http.CallOption) (rsp *BindMobileReply, err error)
	// LoginByOtp 验证码登录
	LoginByOtp(ctx context.Context, req *LoginByOtpRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	// LoginByPassword 密码登录
	LoginByPassword(ctx context.Context, req *LoginByPasswordRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	// Logout 用户退出
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *LogoutReply, err error)
	// Register 用户注册
	Register(ctx context.Context, req *RegisterRequest, opts ...http.CallOption) (rsp *RegisterReply, err error)
	// ResetPassword 找回密码
	ResetPassword(ctx context.Context, req *ResetPasswordRequest, opts ...http.CallOption) (rsp *ResetPasswordReply, err error)
	// UpdateMobile 修改绑定手机号
	UpdateMobile(ctx context.Context, req *UpdateMobileRequest, opts ...http.CallOption) (rsp *UpdateMobileReply, err error)
	// UpdatePassword 修改密码
	UpdatePassword(ctx context.Context, req *UpdatePasswordRequest, opts ...http.CallOption) (rsp *UpdatePasswordReply, err error)
	// UserInfo 获取用户信息
	UserInfo(ctx context.Context, req *UserInfoRequest, opts ...http.CallOption) (rsp *UserInfoReply, err error)
}

type PassportHTTPClientImpl struct {
	cc *http.Client
}

func NewPassportHTTPClient(client *http.Client) PassportHTTPClient {
	return &PassportHTTPClientImpl{client}
}

// BindMobile 绑定手机号
func (c *PassportHTTPClientImpl) BindMobile(ctx context.Context, in *BindMobileRequest, opts ...http.CallOption) (*BindMobileReply, error) {
	var out BindMobileReply
	pattern := "/passport/bind-mobile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPassportBindMobile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoginByOtp 验证码登录
func (c *PassportHTTPClientImpl) LoginByOtp(ctx context.Context, in *LoginByOtpRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/passport/login/otp"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPassportLoginByOtp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoginByPassword 密码登录
func (c *PassportHTTPClientImpl) LoginByPassword(ctx context.Context, in *LoginByPasswordRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/passport/login/password"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPassportLoginByPassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Logout 用户退出
func (c *PassportHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*LogoutReply, error) {
	var out LogoutReply
	pattern := "/passport/logout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPassportLogout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Register 用户注册
func (c *PassportHTTPClientImpl) Register(ctx context.Context, in *RegisterRequest, opts ...http.CallOption) (*RegisterReply, error) {
	var out RegisterReply
	pattern := "/passport/register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPassportRegister))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResetPassword 找回密码
func (c *PassportHTTPClientImpl) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...http.CallOption) (*ResetPasswordReply, error) {
	var out ResetPasswordReply
	pattern := "/passport/reset-password"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPassportResetPassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateMobile 修改绑定手机号
func (c *PassportHTTPClientImpl) UpdateMobile(ctx context.Context, in *UpdateMobileRequest, opts ...http.CallOption) (*UpdateMobileReply, error) {
	var out UpdateMobileReply
	pattern := "/passport/update-mobile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPassportUpdateMobile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePassword 修改密码
func (c *PassportHTTPClientImpl) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...http.CallOption) (*UpdatePasswordReply, error) {
	var out UpdatePasswordReply
	pattern := "/passport/update-password"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPassportUpdatePassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UserInfo 获取用户信息
func (c *PassportHTTPClientImpl) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...http.CallOption) (*UserInfoReply, error) {
	var out UserInfoReply
	pattern := "/passport/user-info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPassportUserInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
