// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/passport/v1/passport.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 用户注册 ==========
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名，规则：3-20位字符
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 密码，规则：6-20位字符
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 确认密码，规则：6-20位字符
	ConfirmPassword string `protobuf:"bytes,3,opt,name=confirm_password,proto3" json:"confirm_password,omitempty"`
	// 手机号，规则：11位数字，选填
	Mobile string `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 验证码，规则：4-6位字符，选填
	Code          string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

func (x *RegisterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RegisterReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 登录凭证
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ========== 密码登录 ==========
type LoginByPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名，规则：3-20位字符
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 密码，规则：6-20位字符
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 图形验证码ID
	CaptchaId string `protobuf:"bytes,3,opt,name=captcha_id,proto3" json:"captcha_id,omitempty"`
	// 图形验证码
	Captcha       string `protobuf:"bytes,4,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByPasswordRequest) Reset() {
	*x = LoginByPasswordRequest{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByPasswordRequest) ProtoMessage() {}

func (x *LoginByPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByPasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginByPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{2}
}

func (x *LoginByPasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginByPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginByPasswordRequest) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *LoginByPasswordRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

// ========== 验证码登录 ==========
type LoginByOtpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 手机号，规则：11位数字
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 验证码
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByOtpRequest) Reset() {
	*x = LoginByOtpRequest{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByOtpRequest) ProtoMessage() {}

func (x *LoginByOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByOtpRequest.ProtoReflect.Descriptor instead.
func (*LoginByOtpRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{3}
}

func (x *LoginByOtpRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginByOtpRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// ========== 登录响应 ==========
type LoginReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 登录凭证
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ========== 用户退出 ==========
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{5}
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{6}
}

// ========== 获取用户信息 ==========
type UserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRequest) Reset() {
	*x = UserInfoRequest{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequest) ProtoMessage() {}

func (x *UserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequest.ProtoReflect.Descriptor instead.
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{7}
}

type UserInfoReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 手机号
	Mobile string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 状态：0=禁用，1=正常
	Status        int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoReply) Reset() {
	*x = UserInfoReply{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReply) ProtoMessage() {}

func (x *UserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReply.ProtoReflect.Descriptor instead.
func (*UserInfoReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfoReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfoReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserInfoReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// ========== 修改密码 ==========
type UpdatePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 旧密码，规则：6-20位字符
	OldPassword string `protobuf:"bytes,1,opt,name=old_password,proto3" json:"old_password,omitempty"`
	// 新密码，规则：6-20位字符
	NewPassword string `protobuf:"bytes,2,opt,name=new_password,proto3" json:"new_password,omitempty"`
	// 确认新密码，规则：6-20位字符
	ConfirmPassword string `protobuf:"bytes,3,opt,name=confirm_password,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type UpdatePasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordReply) Reset() {
	*x = UpdatePasswordReply{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReply) ProtoMessage() {}

func (x *UpdatePasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReply.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{10}
}

// ========== 绑定手机号 ==========
type BindMobileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 手机号，规则：11位数字
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 验证码
	Code          string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindMobileRequest) Reset() {
	*x = BindMobileRequest{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMobileRequest) ProtoMessage() {}

func (x *BindMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMobileRequest.ProtoReflect.Descriptor instead.
func (*BindMobileRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{11}
}

func (x *BindMobileRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *BindMobileRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type BindMobileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindMobileReply) Reset() {
	*x = BindMobileReply{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindMobileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMobileReply) ProtoMessage() {}

func (x *BindMobileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMobileReply.ProtoReflect.Descriptor instead.
func (*BindMobileReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{12}
}

// ========== 修改绑定手机号 ==========
type UpdateMobileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 新手机号，规则：11位数字
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 验证码
	Code          string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMobileRequest) Reset() {
	*x = UpdateMobileRequest{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMobileRequest) ProtoMessage() {}

func (x *UpdateMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMobileRequest.ProtoReflect.Descriptor instead.
func (*UpdateMobileRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateMobileRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpdateMobileRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateMobileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMobileReply) Reset() {
	*x = UpdateMobileReply{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMobileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMobileReply) ProtoMessage() {}

func (x *UpdateMobileReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMobileReply.ProtoReflect.Descriptor instead.
func (*UpdateMobileReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{14}
}

// ========== 找回密码 ==========
type ResetPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 手机号，规则：11位数字
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 短信验证码
	SmsCode string `protobuf:"bytes,2,opt,name=sms_code,proto3" json:"sms_code,omitempty"`
	// 新密码，规则：6-20位字符
	NewPassword string `protobuf:"bytes,3,opt,name=new_password,proto3" json:"new_password,omitempty"`
	// 确认新密码，规则：6-20位字符
	ConfirmPassword string `protobuf:"bytes,4,opt,name=confirm_password,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{15}
}

func (x *ResetPasswordRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ResetPasswordRequest) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ResetPasswordRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type ResetPasswordReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordReply) Reset() {
	*x = ResetPasswordReply{}
	mi := &file_api_passport_v1_passport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReply) ProtoMessage() {}

func (x *ResetPasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_passport_v1_passport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReply.ProtoReflect.Descriptor instead.
func (*ResetPasswordReply) Descriptor() ([]byte, []int) {
	return file_api_passport_v1_passport_proto_rawDescGZIP(), []int{16}
}

var File_api_passport_v1_passport_proto protoreflect.FileDescriptor

const file_api_passport_v1_passport_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/passport/v1/passport.proto\x12\x0fapi.passport.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1copenapi/v3/annotations.proto\"\xa7\x03\n" +
	"\x0fRegisterRequest\x12H\n" +
	"\busername\x18\x01 \x01(\tB,\xe2A\x01\x02\xfaB\x06r\x04\x10\x03\x18\x14\xbaG\x1c\x92\x02\x19用户名，3-20位字符R\busername\x12E\n" +
	"\bpassword\x18\x02 \x01(\tB)\xe2A\x01\x02\xfaB\x06r\x04\x10\x06\x18\x14\xbaG\x19\x92\x02\x16密码，6-20位字符R\bpassword\x12[\n" +
	"\x10confirm_password\x18\x03 \x01(\tB/\xe2A\x01\x02\xfaB\x06r\x04\x10\x06\x18\x14\xbaG\x1f\x92\x02\x1c确认密码，6-20位字符R\x10confirm_password\x12Y\n" +
	"\x06mobile\x18\x04 \x01(\tBA\xe2A\x01\x01\xfaB\x14r\x122\r^1[3-9]\\d{9}$\xd0\x01\x01\xbaG#\x92\x02 手机号，11位数字，选填R\x06mobile\x12K\n" +
	"\x04code\x18\x05 \x01(\tB7\xe2A\x01\x01\xfaB\tr\a\x10\x04\x18\x06\xd0\x01\x01\xbaG$\x92\x02!验证码，4-6位字符，选填R\x04code\"9\n" +
	"\rRegisterReply\x12(\n" +
	"\x05token\x18\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f登录凭证R\x05token\"\xa1\x02\n" +
	"\x16LoginByPasswordRequest\x12H\n" +
	"\busername\x18\x01 \x01(\tB,\xe2A\x01\x02\xfaB\x06r\x04\x10\x03\x18\x14\xbaG\x1c\x92\x02\x19用户名，3-20位字符R\busername\x12E\n" +
	"\bpassword\x18\x02 \x01(\tB)\xe2A\x01\x02\xfaB\x06r\x04\x10\x06\x18\x14\xbaG\x19\x92\x02\x16密码，6-20位字符R\bpassword\x12;\n" +
	"\n" +
	"captcha_id\x18\x03 \x01(\tB\x1b\xe2A\x01\x02\xbaG\x14\x92\x02\x11图形验证码IDR\n" +
	"captcha_id\x129\n" +
	"\acaptcha\x18\x04 \x01(\tB\x1f\xe2A\x01\x02\xbaG\x18\x92\x02\x15图形验证码内容R\acaptcha\"\x9f\x01\n" +
	"\x11LoginByOtpRequest\x12I\n" +
	"\x06mobile\x18\x01 \x01(\tB1\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$\xbaG\x1a\x92\x02\x17手机号，11位数字R\x06mobile\x12?\n" +
	"\x04code\x18\x03 \x01(\tB+\xe2A\x01\x02\xfaB\x06r\x04\x10\x04\x18\x06\xbaG\x1b\x92\x02\x18验证码，4-6位字符R\x04code\"6\n" +
	"\n" +
	"LoginReply\x12(\n" +
	"\x05token\x18\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f登录凭证R\x05token\"\x0f\n" +
	"\rLogoutRequest\"\r\n" +
	"\vLogoutReply\"\x11\n" +
	"\x0fUserInfoRequest\"\xa1\x01\n" +
	"\rUserInfoReply\x12+\n" +
	"\busername\x18\x01 \x01(\tB\x0f\xbaG\f\x92\x02\t用户名R\busername\x12'\n" +
	"\x06mobile\x18\x02 \x01(\tB\x0f\xbaG\f\x92\x02\t手机号R\x06mobile\x12:\n" +
	"\x06status\x18\x03 \x01(\x05B\"\xbaG\x1f\x92\x02\x1c状态：0=禁用，1=正常R\x06status\"\x9b\x02\n" +
	"\x15UpdatePasswordRequest\x12P\n" +
	"\fold_password\x18\x01 \x01(\tB,\xe2A\x01\x02\xfaB\x06r\x04\x10\x06\x18\x14\xbaG\x1c\x92\x02\x19旧密码，6-20位字符R\fold_password\x12P\n" +
	"\fnew_password\x18\x02 \x01(\tB,\xe2A\x01\x02\xfaB\x06r\x04\x10\x06\x18\x14\xbaG\x1c\x92\x02\x19新密码，6-20位字符R\fnew_password\x12^\n" +
	"\x10confirm_password\x18\x03 \x01(\tB2\xe2A\x01\x02\xfaB\x06r\x04\x10\x06\x18\x14\xbaG\"\x92\x02\x1f确认新密码，6-20位字符R\x10confirm_password\"\x15\n" +
	"\x13UpdatePasswordReply\"\xa3\x01\n" +
	"\x11BindMobileRequest\x12M\n" +
	"\x06mobile\x18\x01 \x01(\tB5\xe2A\x01\x02\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$\xbaG\x1a\x92\x02\x17手机号，11位数字R\x06mobile\x12?\n" +
	"\x04code\x18\x02 \x01(\tB+\xe2A\x01\x02\xfaB\x06r\x04\x10\x04\x18\x06\xbaG\x1b\x92\x02\x18验证码，4-6位字符R\x04code\"\x11\n" +
	"\x0fBindMobileReply\"\xa8\x01\n" +
	"\x13UpdateMobileRequest\x12P\n" +
	"\x06mobile\x18\x01 \x01(\tB8\xe2A\x01\x02\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$\xbaG\x1d\x92\x02\x1a新手机号，11位数字R\x06mobile\x12?\n" +
	"\x04code\x18\x02 \x01(\tB+\xe2A\x01\x02\xfaB\x06r\x04\x10\x04\x18\x06\xbaG\x1b\x92\x02\x18验证码，4-6位字符R\x04code\"\x13\n" +
	"\x11UpdateMobileReply\"\xe6\x02\n" +
	"\x14ResetPasswordRequest\x12M\n" +
	"\x06mobile\x18\x01 \x01(\tB5\xe2A\x01\x02\xfaB\x11r\x0f2\r^1[3-9]\\d{9}$\xbaG\x1a\x92\x02\x17手机号，11位数字R\x06mobile\x12M\n" +
	"\bsms_code\x18\x02 \x01(\tB1\xe2A\x01\x02\xfaB\x06r\x04\x10\x04\x18\x06\xbaG!\x92\x02\x1e短信验证码，4-6位字符R\bsms_code\x12P\n" +
	"\fnew_password\x18\x03 \x01(\tB,\xe2A\x01\x02\xfaB\x06r\x04\x10\x06\x18\x14\xbaG\x1c\x92\x02\x19新密码，6-20位字符R\fnew_password\x12^\n" +
	"\x10confirm_password\x18\x04 \x01(\tB2\xe2A\x01\x02\xfaB\x06r\x04\x10\x06\x18\x14\xbaG\"\x92\x02\x1f确认新密码，6-20位字符R\x10confirm_password\"\x14\n" +
	"\x12ResetPasswordReply2\xe5\t\n" +
	"\bPassport\x12|\n" +
	"\bRegister\x12 .api.passport.v1.RegisterRequest\x1a\x1e.api.passport.v1.RegisterReply\".\xbaG\x0e\x12\f用户注册\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/passport/register\x12\x8d\x01\n" +
	"\x0fLoginByPassword\x12'.api.passport.v1.LoginByPasswordRequest\x1a\x1b.api.passport.v1.LoginReply\"4\xbaG\x0e\x12\f密码登录\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/passport/login/password\x12\x81\x01\n" +
	"\n" +
	"LoginByOtp\x12\".api.passport.v1.LoginByOtpRequest\x1a\x1b.api.passport.v1.LoginReply\"2\xbaG\x11\x12\x0f验证码登录\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/passport/login/otp\x12t\n" +
	"\x06Logout\x12\x1e.api.passport.v1.LogoutRequest\x1a\x1c.api.passport.v1.LogoutReply\",\xbaG\x0e\x12\f用户退出\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/passport/logout\x12\x80\x01\n" +
	"\bUserInfo\x12 .api.passport.v1.UserInfoRequest\x1a\x1e.api.passport.v1.UserInfoReply\"2\xbaG\x14\x12\x12获取用户信息\x82\xd3\xe4\x93\x02\x15\x12\x13/passport/user-info\x12\x95\x01\n" +
	"\x0eUpdatePassword\x12&.api.passport.v1.UpdatePasswordRequest\x1a$.api.passport.v1.UpdatePasswordReply\"5\xbaG\x0e\x12\f修改密码\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/passport/update-password\x12\x88\x01\n" +
	"\n" +
	"BindMobile\x12\".api.passport.v1.BindMobileRequest\x1a .api.passport.v1.BindMobileReply\"4\xbaG\x11\x12\x0f绑定手机号\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/passport/bind-mobile\x12\x96\x01\n" +
	"\fUpdateMobile\x12$.api.passport.v1.UpdateMobileRequest\x1a\".api.passport.v1.UpdateMobileReply\"<\xbaG\x17\x12\x15修改绑定手机号\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/passport/update-mobile\x12\x91\x01\n" +
	"\rResetPassword\x12%.api.passport.v1.ResetPasswordRequest\x1a#.api.passport.v1.ResetPasswordReply\"4\xbaG\x0e\x12\f找回密码\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/passport/reset-passwordBU\n" +
	"\x0fapi.passport.v1P\x01Z@github.com/sober-studio/bubble-boot-go-kratos/api/passport/v1;v1b\x06proto3"

var (
	file_api_passport_v1_passport_proto_rawDescOnce sync.Once
	file_api_passport_v1_passport_proto_rawDescData []byte
)

func file_api_passport_v1_passport_proto_rawDescGZIP() []byte {
	file_api_passport_v1_passport_proto_rawDescOnce.Do(func() {
		file_api_passport_v1_passport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_passport_v1_passport_proto_rawDesc), len(file_api_passport_v1_passport_proto_rawDesc)))
	})
	return file_api_passport_v1_passport_proto_rawDescData
}

var file_api_passport_v1_passport_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_passport_v1_passport_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: api.passport.v1.RegisterRequest
	(*RegisterReply)(nil),          // 1: api.passport.v1.RegisterReply
	(*LoginByPasswordRequest)(nil), // 2: api.passport.v1.LoginByPasswordRequest
	(*LoginByOtpRequest)(nil),      // 3: api.passport.v1.LoginByOtpRequest
	(*LoginReply)(nil),             // 4: api.passport.v1.LoginReply
	(*LogoutRequest)(nil),          // 5: api.passport.v1.LogoutRequest
	(*LogoutReply)(nil),            // 6: api.passport.v1.LogoutReply
	(*UserInfoRequest)(nil),        // 7: api.passport.v1.UserInfoRequest
	(*UserInfoReply)(nil),          // 8: api.passport.v1.UserInfoReply
	(*UpdatePasswordRequest)(nil),  // 9: api.passport.v1.UpdatePasswordRequest
	(*UpdatePasswordReply)(nil),    // 10: api.passport.v1.UpdatePasswordReply
	(*BindMobileRequest)(nil),      // 11: api.passport.v1.BindMobileRequest
	(*BindMobileReply)(nil),        // 12: api.passport.v1.BindMobileReply
	(*UpdateMobileRequest)(nil),    // 13: api.passport.v1.UpdateMobileRequest
	(*UpdateMobileReply)(nil),      // 14: api.passport.v1.UpdateMobileReply
	(*ResetPasswordRequest)(nil),   // 15: api.passport.v1.ResetPasswordRequest
	(*ResetPasswordReply)(nil),     // 16: api.passport.v1.ResetPasswordReply
}
var file_api_passport_v1_passport_proto_depIdxs = []int32{
	0,  // 0: api.passport.v1.Passport.Register:input_type -> api.passport.v1.RegisterRequest
	2,  // 1: api.passport.v1.Passport.LoginByPassword:input_type -> api.passport.v1.LoginByPasswordRequest
	3,  // 2: api.passport.v1.Passport.LoginByOtp:input_type -> api.passport.v1.LoginByOtpRequest
	5,  // 3: api.passport.v1.Passport.Logout:input_type -> api.passport.v1.LogoutRequest
	7,  // 4: api.passport.v1.Passport.UserInfo:input_type -> api.passport.v1.UserInfoRequest
	9,  // 5: api.passport.v1.Passport.UpdatePassword:input_type -> api.passport.v1.UpdatePasswordRequest
	11, // 6: api.passport.v1.Passport.BindMobile:input_type -> api.passport.v1.BindMobileRequest
	13, // 7: api.passport.v1.Passport.UpdateMobile:input_type -> api.passport.v1.UpdateMobileRequest
	15, // 8: api.passport.v1.Passport.ResetPassword:input_type -> api.passport.v1.ResetPasswordRequest
	1,  // 9: api.passport.v1.Passport.Register:output_type -> api.passport.v1.RegisterReply
	4,  // 10: api.passport.v1.Passport.LoginByPassword:output_type -> api.passport.v1.LoginReply
	4,  // 11: api.passport.v1.Passport.LoginByOtp:output_type -> api.passport.v1.LoginReply
	6,  // 12: api.passport.v1.Passport.Logout:output_type -> api.passport.v1.LogoutReply
	8,  // 13: api.passport.v1.Passport.UserInfo:output_type -> api.passport.v1.UserInfoReply
	10, // 14: api.passport.v1.Passport.UpdatePassword:output_type -> api.passport.v1.UpdatePasswordReply
	12, // 15: api.passport.v1.Passport.BindMobile:output_type -> api.passport.v1.BindMobileReply
	14, // 16: api.passport.v1.Passport.UpdateMobile:output_type -> api.passport.v1.UpdateMobileReply
	16, // 17: api.passport.v1.Passport.ResetPassword:output_type -> api.passport.v1.ResetPasswordReply
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_passport_v1_passport_proto_init() }
func file_api_passport_v1_passport_proto_init() {
	if File_api_passport_v1_passport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_passport_v1_passport_proto_rawDesc), len(file_api_passport_v1_passport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_passport_v1_passport_proto_goTypes,
		DependencyIndexes: file_api_passport_v1_passport_proto_depIdxs,
		MessageInfos:      file_api_passport_v1_passport_proto_msgTypes,
	}.Build()
	File_api_passport_v1_passport_proto = out.File
	file_api_passport_v1_passport_proto_goTypes = nil
	file_api_passport_v1_passport_proto_depIdxs = nil
}
